### ISSUE TITLE
github-stats deploy failed

### ISSUE THREAD

**Issue by insolor** [astrochun/github-stats#5]
I've made a new github-stats repository from this template, and now it fails every time it tries to deploy. It complains about missing csv files (it doesn't get statistics, I guess?):

![2021-06-21 08 38 30 github com 385bdcc7f1f2](https://user-images.githubusercontent.com/2442833/122712115-137a1180-d26c-11eb-8556-9c06c5e09500.png)

An example of failed build: https://github.com/insolor/github-stats/runs/2871689313?check_suite_focus=true

**Comment by astrochun** [comment]
This issue seems to stem from not specifying the GitHub API token. Are you sure `GH_TOKEN` is specified and that token is active?

**Comment by insolor** [comment]
Yes, you are right, that was the case. But now it fails because of some ImportError:
```
Traceback (most recent call last):
  File "/usr/local/bin/gts_run_all_repos", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/scripts/gts_run_all_repos", line 39, in <module>
    gts_run.get_top_paths(args.user, args.token, repo_name,
  File "/github_stats_pages/gts_run.py", line 28, in get_top_paths
    pandas_write_buffer(df, ['path', 'count', 'uniques'], reponame)
  File "/github_stats_pages/gts_run.py", line 42, in pandas_write_buffer
    df[columns].to_markdown(buffer, index=False)
  File "/usr/local/lib/python3.9/site-packages/pandas-1.3.0rc1-py3.9-linux-x86_64.egg/pandas/core/frame.py", line 2568, in to_markdown
    tabulate = import_optional_dependency("tabulate")
  File "/usr/local/lib/python3.9/site-packages/pandas-1.3.0rc1-py3.9-linux-x86_64.egg/pandas/compat/_optional.py", line 141, in import_optional_dependency
    raise ImportError(msg)
```
Build log: https://github.com/insolor/github-stats/runs/2872421454?check_suite_focus=true

**Comment by astrochun** [comment]
Glad the token was an easy fix.

Yes, I had noticed this as well when I was investigating your token issue late last night.  I looked at the logs for my builds. It seems that `pandas==1.3.0` was deployed when I was away this past week. That requires a newer version of `tabulate`. I'll be deploying a fix later today, which will update the `latest` tag for `github-stats-pages`. You can check on the status in astrochun/github-stats-pages#59.

Sorry for the delay.

**Comment by astrochun** [comment]
I believe the bug has been patched as I successfully ran the action: https://github.com/astrochun/test-github-stats/runs/2880311419?check_suite_focus=true.

**Comment by insolor** [comment]
Yes, I can confirm, now it works. Thanks for the assistance :)
